// ===== LANGUAGE TRANSLATIONS SYSTEM =====
const translations = {
    de: {
        nav_home: "Startseite",
        nav_expertise: "Expertise",
        nav_projects: "Projekte",
        nav_contact: "Kontakt",
        nav_cta: "Loslegen",
        hero_badge: "Verfügbar für exklusive Projekte",
        hero_title_line1: "Digitale",
        hero_title_line2: "Meisterwerke",
        hero_subtitle: "Visionen in Premium-Web-Erlebnisse verwandeln durch modernste Technologie und unübertroffene Design-Exzellenz.",
        hero_btn_portfolio: "Portfolio ansehen",
        hero_btn_talk: "Kontakt aufnehmen",
        hero_stat1_label: "Abgeschlossene Projekte",
        hero_stat2_label: "Kundenzufriedenheit",
        hero_stat3_label: "Jahre Erfahrung",
        hero_scroll: "Scrollen um zu entdecken",
        expertise_tag: "EXPERTISE",
        expertise_title: "Full-Stack Meisterschaft",
        expertise_subtitle: "Nutzung modernster Technologien zur Entwicklung skalierbarer, performanter und schöner digitaler Lösungen.",
        expertise_frontend_title: "Frontend Exzellenz",
        expertise_frontend_desc: "React, Vue.js, Next.js, TypeScript, Three.js, GSAP, Tailwind CSS",
        expertise_backend_title: "Backend Architektur",
        expertise_backend_desc: "Node.js, Python, PostgreSQL, MongoDB, Redis, AWS, Docker",
        expertise_design_title: "UI/UX Design",
        expertise_design_desc: "Figma, Adobe XD, Responsives Design, Motion Design, Design-Systeme",
        expertise_optimization_title: "Performance-Optimierung",
        expertise_optimization_desc: "SEO, Core Web Vitals, Lighthouse, Bundle-Optimierung, CDN",
        services_tag: "UNSER ANGEBOT",
        services_title: "Wir erstellen JEDE Art von Website",
        services_subtitle: "Maßgeschneiderte Lösungen für Ihre spezifischen Anforderungen.",
        service_ecommerce: "Online-Shops / E-Commerce",
        service_blog: "Blogs & Content-Plattformen",
        service_corporate: "Corporate Websites",
        service_portfolio: "Portfolio-Websites",
        service_webapp: "Web-Apps",
        service_landing: "Landing Pages",
        service_saas: "SaaS-Plattformen",
        service_api: "API-Integrationen",
        projects_tag: "PORTFOLIO",
        projects_title: "Ausgewählte Arbeiten",
        projects_subtitle: "Eine Auswahl an Premium-Projekten, die Innovation und Handwerkskunst zeigen.",
        project1_tag: "E-Commerce Plattform",
        project1_title: "Luxus Mode Marktplatz",
        project1_desc: "Hochleistungs E-Commerce-Plattform mit Echtzeit-Inventar, KI-gestützten Empfehlungen und nahtlosem Checkout.",
        project2_tag: "SaaS Anwendung",
        project2_title: "Analytics Dashboard",
        project2_desc: "Echtzeit-Analyseplattform mit interaktiver Datenvisualisierung.",
        project3_tag: "Web3 Plattform",
        project3_title: "NFT Marktplatz",
        project3_desc: "Dezentraler Marktplatz für digitale Sammlerstücke und Kunst.",
        contact_tag: "KONTAKT",
        contact_title: "Gemeinsam etwas Außergewöhnliches schaffen",
        contact_desc: "Bereit, Ihre Vision in die Realität umzusetzen? Lassen Sie uns über Ihr nächstes Projekt sprechen und erkunden, wie wir gemeinsam etwas Außergewöhnliches schaffen können.",
        contact_email_label: "E-Mail",
        contact_email_value: "hello@bevadiam.com",
        contact_location_label: "Standort",
        contact_location_value: "Deutschland, Österreich, Schweiz, Russland",
        form_name: "Name",
        form_name_placeholder: "Ihr Name",
        form_email: "E-Mail",
        form_email_placeholder: "ihre@email.de",
        form_phone: "Telefon",
        form_phone_placeholder: "+49 123 4567890",
        form_project: "Projekttyp",
        form_opt_webapp: "Webanwendung",
        form_opt_ecommerce: "E-Commerce / Shop",
        form_opt_mobile: "Mobile App",
        form_opt_design: "UI/UX Design",
        form_opt_consulting: "Beratung & Strategie",
        form_opt_landing: "Landing Page",
        form_opt_saas: "SaaS-Plattform",
        form_opt_api: "API-Integration",
        form_opt_corporate: "Corporate Website",
        form_opt_seo: "SEO & Performance",
        form_message: "Nachricht",
        form_message_placeholder: "Erzählen Sie mir von Ihrem Projekt...",
        form_submit: "Nachricht senden",
        form_sending: "Wird gesendet...",
        form_sent: "Nachricht gesendet!",
        footer_tagline: "Erschaffung erstklassiger digitaler Erlebnisse",
        footer_services: "Leistungen",
        footer_service1: "Webentwicklung",
        footer_service2: "UI/UX Design",
        footer_service3: "Beratung",
        footer_connect: "Verbinden",
        footer_copyright: "© 2026 BevaDiam. Alle Rechte vorbehalten.",
        pwa_install_title: "App installieren",
        pwa_install_desc: "Holen Sie sich das beste Erlebnis mit unserer App",
        pwa_install_button: "Installieren",
        offline_message: "Sie sind offline"
    },
    en: {
        nav_home: "Home",
        nav_expertise: "Expertise",
        nav_projects: "Projects",
        nav_contact: "Contact",
        nav_cta: "Get Started",
        hero_badge: "Available for exclusive projects",
        hero_title_line1: "Crafting Digital",
        hero_title_line2: "Masterpieces",
        hero_subtitle: "Transforming visions into premium web experiences through cutting-edge technology and unparalleled design excellence.",
        hero_btn_portfolio: "View Portfolio",
        hero_btn_talk: "Let's Talk",
        hero_stat1_label: "Projects Delivered",
        hero_stat2_label: "Client Satisfaction",
        hero_stat3_label: "Years Experience",
        hero_scroll: "Scroll to explore",
        expertise_tag: "EXPERTISE",
        expertise_title: "Mastering the Full Stack",
        expertise_subtitle: "Leveraging cutting-edge technologies to build scalable, performant, and beautiful digital solutions.",
        expertise_frontend_title: "Frontend Excellence",
        expertise_frontend_desc: "React, Vue.js, Next.js, TypeScript, Three.js, GSAP, Tailwind CSS",
        expertise_backend_title: "Backend Architecture",
        expertise_backend_desc: "Node.js, Python, PostgreSQL, MongoDB, Redis, AWS, Docker",
        expertise_design_title: "UI/UX Design",
        expertise_design_desc: "Figma, Adobe XD, Responsive Design, Motion Design, Design Systems",
        expertise_optimization_title: "Performance Optimization",
        expertise_optimization_desc: "SEO, Core Web Vitals, Lighthouse, Bundle Optimization, CDN",
        services_tag: "OUR SERVICES",
        services_title: "We create ANY type of website",
        services_subtitle: "Tailored solutions for your specific requirements.",
        service_ecommerce: "Online Shops / E-Commerce",
        service_blog: "Blogs & Content Platforms",
        service_corporate: "Corporate Websites",
        service_portfolio: "Portfolio Websites",
        service_webapp: "Web Apps",
        service_landing: "Landing Pages",
        service_saas: "SaaS Platforms",
        service_api: "API Integrations",
        projects_tag: "PORTFOLIO",
        projects_title: "Featured Work",
        projects_subtitle: "A selection of premium projects that showcase innovation and craftsmanship.",
        project1_tag: "E-Commerce Platform",
        project1_title: "Luxury Fashion Marketplace",
        project1_desc: "High-performance e-commerce platform with real-time inventory, AI-powered recommendations, and seamless checkout experience.",
        project2_tag: "SaaS Application",
        project2_title: "Analytics Dashboard",
        project2_desc: "Real-time analytics platform with interactive data visualization.",
        project3_tag: "Web3 Platform",
        project3_title: "NFT Marketplace",
        project3_desc: "Decentralized marketplace for digital collectibles and art.",
        contact_tag: "GET IN TOUCH",
        contact_title: "Let's Create Something Extraordinary",
        contact_desc: "Ready to transform your vision into reality? Let's discuss your next project and explore how we can create something exceptional together.",
        contact_email_label: "Email",
        contact_email_value: "hello@bevadiam.com",
        contact_location_label: "Location",
        contact_location_value: "Germany, Austria, Switzerland, Russia",
        form_name: "Name",
        form_name_placeholder: "Your name",
        form_email: "Email",
        form_email_placeholder: "your@email.com",
        form_phone: "Phone",
        form_phone_placeholder: "+1 234 567 890",
        form_project: "Project Type",
        form_opt_webapp: "Web Application",
        form_opt_ecommerce: "E-Commerce / Shop",
        form_opt_mobile: "Mobile App",
        form_opt_design: "UI/UX Design",
        form_opt_consulting: "Consulting & Strategy",
        form_opt_landing: "Landing Page",
        form_opt_saas: "SaaS Platform",
        form_opt_api: "API Integration",
        form_opt_corporate: "Corporate Website",
        form_opt_seo: "SEO & Performance",
        form_message: "Message",
        form_message_placeholder: "Tell me about your project...",
        form_submit: "Send Message",
        form_sending: "Sending...",
        form_sent: "Message Sent!",
        footer_tagline: "Crafting premium digital experiences",
        footer_services: "Services",
        footer_service1: "Web Development",
        footer_service2: "UI/UX Design",
        footer_service3: "Consulting",
        footer_connect: "Connect",
        footer_copyright: "© 2026 BevaDiam. All rights reserved.",
        pwa_install_title: "Install App",
        pwa_install_desc: "Get the best experience with our app",
        pwa_install_button: "Install",
        offline_message: "You are offline"
    },
    ru: {
        nav_home: "Главная",
        nav_expertise: "Экспертиза",
        nav_projects: "Проекты",
        nav_contact: "Контакты",
        nav_cta: "Начать",
        hero_badge: "Доступен для эксклюзивных проектов",
        hero_title_line1: "Создание цифровых",
        hero_title_line2: "шедевров",
        hero_subtitle: "Превращаем видение в премиальные веб-решения с помощью передовых технологий и непревзойденного дизайна.",
        hero_btn_portfolio: "Портфолио",
        hero_btn_talk: "Связаться",
        hero_stat1_label: "Реализованных проектов",
        hero_stat2_label: "Удовлетворенность клиентов",
        hero_stat3_label: "Лет опыта",
        hero_scroll: "Прокрутите для изучения",
        expertise_tag: "ЭКСПЕРТИЗА",
        expertise_title: "Полный стек разработки",
        expertise_subtitle: "Используем передовые технологии для создания масштабируемых, производительных и красивых цифровых решений.",
        expertise_frontend_title: "Frontend превосходство",
        expertise_frontend_desc: "React, Vue.js, Next.js, TypeScript, Three.js, GSAP, Tailwind CSS",
        expertise_backend_title: "Backend архитектура",
        expertise_backend_desc: "Node.js, Python, PostgreSQL, MongoDB, Redis, AWS, Docker",
        expertise_design_title: "UI/UX дизайн",
        expertise_design_desc: "Figma, Adobe XD, адаптивный дизайн, моушн-дизайн, дизайн-системы",
        expertise_optimization_title: "Оптимизация производительности",
        expertise_optimization_desc: "SEO, Core Web Vitals, Lighthouse, оптимизация бандлов, CDN",
        services_tag: "НАШИ УСЛУГИ",
        services_title: "Мы создаем ЛЮБЫЕ типы сайтов",
        services_subtitle: "Индивидуальные решения для ваших конкретных требований.",
        service_ecommerce: "Интернет-магазины / E-Commerce",
        service_blog: "Блоги и контент-платформы",
        service_corporate: "Корпоративные сайты",
        service_portfolio: "Сайты-портфолио",
        service_webapp: "Веб-приложения",
        service_landing: "Лендинги",
        service_saas: "SaaS-платформы",
        service_api: "API интеграции",
        projects_tag: "ПОРТФОЛИО",
        projects_title: "Избранные работы",
        projects_subtitle: "Подборка премиальных проектов, демонстрирующих инновации и мастерство.",
        project1_tag: "E-Commerce платформа",
        project1_title: "Маркетплейс люксовой моды",
        project1_desc: "Высокопроизводительная платформа электронной коммерции с инвентаризацией в реальном времени, рекомендациями на основе ИИ и бесшовной оплатой.",
        project2_tag: "SaaS приложение",
        project2_title: "Аналитическая панель",
        project2_desc: "Платформа аналитики в реальном времени с интерактивной визуализацией данных.",
        project3_tag: "Web3 платформа",
        project3_title: "NFT маркетплейс",
        project3_desc: "Децентрализованный маркетплейс для цифровых коллекционных предметов и искусства.",
        contact_tag: "СВЯЖИТЕСЬ С НАМИ",
        contact_title: "Давайте создадим что-то выдающееся",
        contact_desc: "Готовы воплотить свое видение в реальность? Давайте обсудим ваш следующий проект и рассмотрим, как мы можем создать что-то исключительное вместе.",
        contact_email_label: "Email",
        contact_email_value: "hello@bevadiam.com",
        contact_location_label: "Местоположение",
        contact_location_value: "Германия, Австрия, Швейцария, Россия",
        form_name: "Имя",
        form_name_placeholder: "Ваше имя",
        form_email: "Email",
        form_email_placeholder: "ваш@email.com",
        form_phone: "Телефон",
        form_phone_placeholder: "+7 999 123 45 67",
        form_project: "Тип проекта",
        form_opt_webapp: "Веб-приложение",
        form_opt_ecommerce: "E-Commerce / Магазин",
        form_opt_mobile: "Мобильное приложение",
        form_opt_design: "UI/UX Дизайн",
        form_opt_consulting: "Консультации",
        form_opt_landing: "Лендинг",
        form_opt_saas: "SaaS-платформа",
        form_opt_api: "API интеграция",
        form_opt_corporate: "Корпоративный сайт",
        form_opt_seo: "SEO и Производительность",
        form_message: "Сообщение",
        form_message_placeholder: "Расскажите о вашем проекте...",
        form_submit: "Отправить сообщение",
        form_sending: "Отправка...",
        form_sent: "Сообщение отправлено!",
        footer_tagline: "Создаем премиальные цифровые решения",
        footer_services: "Услуги",
        footer_service1: "Веб-разработка",
        footer_service2: "UI/UX дизайн",
        footer_service3: "Консультирование",
        footer_connect: "Связаться",
        footer_copyright: "© 2026 BevaDiam. Все права защищены.",
        pwa_install_title: "Установить приложение",
        pwa_install_desc: "Получите лучший опыт с нашим приложением",
        pwa_install_button: "Установить",
        offline_message: "Вы не в сети"
    }
};

let currentLanguage = localStorage.getItem('language') || 'de';

function changeLanguage(lang) {
    currentLanguage = lang;
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang; // Set HTML lang attribute for SEO
    updateContent();
    updateLanguageButton();
}

function updateContent() {
    const t = translations[currentLanguage];
    
    // Efficiently update all elements with data-i18n attribute
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        const translation = t[key];

        if (translation) {
            if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
                element.placeholder = translation;
            } else {
                element.textContent = translation;
            }
        }
    });
}

function updateLanguageButton() {
    const langText = document.querySelector('.lang-current');
    if (langText) {
        langText.textContent = currentLanguage.toUpperCase();
    }
}

// Initialize on page load
document.addEventListener('DOMContentLoaded', () => {
    updateContent();
    updateLanguageButton();
});
